version: "3"

services:
    database:
        image: timescale/timescaledb:latest-pg17
        command: postgres -c shared_preload_libraries=timescaledb
        restart: unless-stopped
        ports:   
            - 5431:5432             
        volumes: 
            - pg_data:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            LANG: ${LANG}
            LC_COLLATE: ${LC_COLLATE}
            LC_CTYPE: ${LC_CTYPE}
        networks:
        - backend
    app:
        build:
            context: ./php
        volumes:
            - ../:/var/www/symfony:cached
            - app_var:/var/www/symfony/var
            - app_vendor:/var/www/symfony/vendor
      
        networks:
            - backend
    web:
        build:
            context: ./nginx
        volumes: 
            - ../:/var/www/symfony:cached
        #     - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        #     - ./logs/nginx:/var/log/nginx
        ports:
            - 80:80
        env_file:
            - .env.nginx
        networks:
            - backend

volumes:
    app_var:
    app_vendor:
    pg_data:

networks:
    backend:
